import type { AiGeneratedMedia } from '../domain/ai';
import type { ProjectRole } from '../domain/collaboration';
import type { AssetRef } from '../domain/model';

const approverRoles = new Set<ProjectRole>(['owner', 'director']);

export function approveGeneratedMedia(output: AiGeneratedMedia, userId: string, role: ProjectRole, at = new Date().toISOString()): AiGeneratedMedia {
  if (!approverRoles.has(role)) throw new Error(`Role ${role} cannot approve generated media.`);
  if (output.status !== 'generated') throw new Error(`Only generated media can be approved; current status is ${output.status}.`);
  return { ...structuredClone(output), status: 'approved', approvedBy: userId, approvedAt: at };
}

export function rejectGeneratedMedia(output: AiGeneratedMedia, userId: string, role: ProjectRole, at = new Date().toISOString()): AiGeneratedMedia {
  if (!approverRoles.has(role)) throw new Error(`Role ${role} cannot reject generated media.`);
  if (output.status !== 'generated') throw new Error(`Only generated media can be rejected; current status is ${output.status}.`);
  return { ...structuredClone(output), status: 'rejected', rejectedBy: userId, rejectedAt: at };
}

export function approvedGeneratedMediaToAsset(output: AiGeneratedMedia, userId: string): AssetRef {
  if (output.status !== 'approved') throw new Error('Generated media must be approved before Asset Registry promotion.');
  if (!output.uri) throw new Error('Approved generated media has no URI.');
  const id = output.id.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  if (!id) throw new Error('Generated media has no valid Asset ID.');
  return {
    id,
    name: `${output.task} · ${output.sourceShotId}`,
    category: output.task,
    version: 'v001',
    uri: output.uri,
    license: 'generated-project-use',
    owner: userId,
    unitScaleMeters: 1,
    contentHashSha256: output.contentHashSha256,
    provenance: {
      source: 'generated',
      sourceUri: output.uri,
      recordedAt: output.generatedAt,
      recordedBy: output.approvedBy ?? userId,
      parentAssetId: output.sourceShotId,
    },
    diagnostics: [{ severity: 'info', code: 'ai-provenance', message: `Generated by ${output.profile.modelId}@${output.profile.revision}; prompt ${output.promptHashSha256}; controls ${output.controlHashSha256}; source Shot ${output.sourceShotHashSha256}.` }],
  };
}
